USE [UserManagment]
GO
/****** Object:  Table [dbo].[USER_LOG]    Script Date: 28-08-2023 17:01:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USER_LOG](
	[USER_LOG_ID] [int] IDENTITY(1,1) NOT NULL,
	[USER_NAME] [varchar](20) NULL,
	[LOGIN_DATE] [datetime] NULL,
	[UserId] [int] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserDetail]    Script Date: 28-08-2023 17:01:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserDetail](
	[UserId] [int] IDENTITY(1,1) NOT NULL,
	[FIRST_NAME] [varchar](20) NULL,
	[LAST_NAME] [varchar](20) NULL,
	[USER_NAME] [varchar](20) NULL,
	[USER_PASSWORD] [varchar](20) NULL,
	[USER_TYPE] [int] NULL,
	[LOGIN_DATE] [nchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[USER_LOG] ON 
GO
INSERT [dbo].[USER_LOG] ([USER_LOG_ID], [USER_NAME], [LOGIN_DATE], [UserId]) VALUES (1, N'KAMALRAJPUT24', CAST(N'2023-08-28T12:45:43.313' AS DateTime), 3)
GO
INSERT [dbo].[USER_LOG] ([USER_LOG_ID], [USER_NAME], [LOGIN_DATE], [UserId]) VALUES (2, N'KAMALRAJPUT24', CAST(N'2023-08-28T13:10:07.957' AS DateTime), 3)
GO
INSERT [dbo].[USER_LOG] ([USER_LOG_ID], [USER_NAME], [LOGIN_DATE], [UserId]) VALUES (3, N'KAMALRAJPUT24', CAST(N'2023-08-28T14:16:21.877' AS DateTime), 3)
GO
INSERT [dbo].[USER_LOG] ([USER_LOG_ID], [USER_NAME], [LOGIN_DATE], [UserId]) VALUES (4, N'KAMALRAJPUT24', CAST(N'2023-08-28T14:17:47.757' AS DateTime), 3)
GO
INSERT [dbo].[USER_LOG] ([USER_LOG_ID], [USER_NAME], [LOGIN_DATE], [UserId]) VALUES (9, N'KAMALRAJPUT24', CAST(N'2023-08-28T15:10:03.810' AS DateTime), 3)
GO
INSERT [dbo].[USER_LOG] ([USER_LOG_ID], [USER_NAME], [LOGIN_DATE], [UserId]) VALUES (5, N'ABC_TEST', CAST(N'2023-08-28T14:20:11.867' AS DateTime), 4)
GO
INSERT [dbo].[USER_LOG] ([USER_LOG_ID], [USER_NAME], [LOGIN_DATE], [UserId]) VALUES (6, N'KAMALRAJPUT24', CAST(N'2023-08-28T14:20:39.753' AS DateTime), 3)
GO
INSERT [dbo].[USER_LOG] ([USER_LOG_ID], [USER_NAME], [LOGIN_DATE], [UserId]) VALUES (7, N'XYZ_TEST', CAST(N'2023-08-28T14:35:06.000' AS DateTime), 5)
GO
INSERT [dbo].[USER_LOG] ([USER_LOG_ID], [USER_NAME], [LOGIN_DATE], [UserId]) VALUES (8, N'KAMALRAJPUT24', CAST(N'2023-08-28T15:05:44.100' AS DateTime), 3)
GO
INSERT [dbo].[USER_LOG] ([USER_LOG_ID], [USER_NAME], [LOGIN_DATE], [UserId]) VALUES (10, N'ABHI_TEST', CAST(N'2023-08-28T15:54:20.320' AS DateTime), 8)
GO
INSERT [dbo].[USER_LOG] ([USER_LOG_ID], [USER_NAME], [LOGIN_DATE], [UserId]) VALUES (11, N'KAMALRAJPUT24', CAST(N'2023-08-28T16:02:22.897' AS DateTime), 3)
GO
INSERT [dbo].[USER_LOG] ([USER_LOG_ID], [USER_NAME], [LOGIN_DATE], [UserId]) VALUES (12, N'ABHI_TEST', CAST(N'2023-08-28T16:02:57.523' AS DateTime), 8)
GO
INSERT [dbo].[USER_LOG] ([USER_LOG_ID], [USER_NAME], [LOGIN_DATE], [UserId]) VALUES (13, N'ABHI_TEST', CAST(N'2023-08-28T16:04:25.983' AS DateTime), 8)
GO
INSERT [dbo].[USER_LOG] ([USER_LOG_ID], [USER_NAME], [LOGIN_DATE], [UserId]) VALUES (14, N'ABHI_TEST', CAST(N'2023-08-28T16:06:21.807' AS DateTime), 8)
GO
INSERT [dbo].[USER_LOG] ([USER_LOG_ID], [USER_NAME], [LOGIN_DATE], [UserId]) VALUES (15, N'ABHI_TEST', CAST(N'2023-08-28T16:07:10.303' AS DateTime), 8)
GO
INSERT [dbo].[USER_LOG] ([USER_LOG_ID], [USER_NAME], [LOGIN_DATE], [UserId]) VALUES (16, N'ABHI_TEST', CAST(N'2023-08-28T16:36:19.433' AS DateTime), 8)
GO
SET IDENTITY_INSERT [dbo].[USER_LOG] OFF
GO
SET IDENTITY_INSERT [dbo].[UserDetail] ON 
GO
INSERT [dbo].[UserDetail] ([UserId], [FIRST_NAME], [LAST_NAME], [USER_NAME], [USER_PASSWORD], [USER_TYPE], [LOGIN_DATE]) VALUES (1, N'rahul', N'patel', N'rahul111', N'123456', NULL, NULL)
GO
INSERT [dbo].[UserDetail] ([UserId], [FIRST_NAME], [LAST_NAME], [USER_NAME], [USER_PASSWORD], [USER_TYPE], [LOGIN_DATE]) VALUES (2, N'Test', N'ABC', N'test_abc', N'123456', 1, NULL)
GO
INSERT [dbo].[UserDetail] ([UserId], [FIRST_NAME], [LAST_NAME], [USER_NAME], [USER_PASSWORD], [USER_TYPE], [LOGIN_DATE]) VALUES (3, N'KAMAL', N'RAJPUT', N'KAMALRAJPUT24', N'123456', 1, N'Aug 28 202')
GO
INSERT [dbo].[UserDetail] ([UserId], [FIRST_NAME], [LAST_NAME], [USER_NAME], [USER_PASSWORD], [USER_TYPE], [LOGIN_DATE]) VALUES (4, N'ABC', N'TEST', N'ABC_TEST', N'123456', 2, N'2023-08-28')
GO
INSERT [dbo].[UserDetail] ([UserId], [FIRST_NAME], [LAST_NAME], [USER_NAME], [USER_PASSWORD], [USER_TYPE], [LOGIN_DATE]) VALUES (5, N'XYZ', N'TEST', N'XYZ_TEST', N'123456', 3, N'2023-08-28')
GO
INSERT [dbo].[UserDetail] ([UserId], [FIRST_NAME], [LAST_NAME], [USER_NAME], [USER_PASSWORD], [USER_TYPE], [LOGIN_DATE]) VALUES (6, N'DEF', N'TEST', N'DEF_TEST', N'123456', 3, N'2023-08-28')
GO
INSERT [dbo].[UserDetail] ([UserId], [FIRST_NAME], [LAST_NAME], [USER_NAME], [USER_PASSWORD], [USER_TYPE], [LOGIN_DATE]) VALUES (7, N'JKH', N'TEST', N'JKH_TEST', N'123456', 3, N'2023-08-28')
GO
INSERT [dbo].[UserDetail] ([UserId], [FIRST_NAME], [LAST_NAME], [USER_NAME], [USER_PASSWORD], [USER_TYPE], [LOGIN_DATE]) VALUES (8, N'ABHI', N'TEST1', N'ABHI_TEST', N'123456', 3, N'2023-08-28')
GO
SET IDENTITY_INSERT [dbo].[UserDetail] OFF
GO
/****** Object:  StoredProcedure [dbo].[SP_USERDETAIL]    Script Date: 28-08-2023 17:01:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_USERDETAIL]
(
@UserId	int	=NULL,
@FIRST_NAME	varchar(20)	=NULL,
@LAST_NAME	varchar(20)	=NULL,
@USER_NAME	varchar(20)	=NULL,
@USER_PASSWORD	varchar(20)	=NULL,
@USER_TYPE	int	=NULL,
@LOGIN_DATE DATETIME = NULL,
@MODE VARCHAR(20)=NULL
)
AS
BEGIN
   IF(@MODE = 'INSERT')
   BEGIN
    INSERT into UserDetail(FIRST_NAME,LAST_NAME,USER_NAME,USER_PASSWORD,USER_TYPE,LOGIN_DATE) values(@FIRST_NAME,@LAST_NAME,@USER_NAME,@USER_PASSWORD,@USER_TYPE,SYSDATETIME());
   END
   ELSE IF(@MODE = 'UPDATE')
   BEGIN
   UPDATE UserDetail SET FIRST_NAME=@FIRST_NAME,LAST_NAME=@LAST_NAME
   ,USER_NAME=@USER_NAME,USER_PASSWORD=@USER_PASSWORD,USER_TYPE=@USER_TYPE
   ,LOGIN_DATE=SYSDATETIME()
    WHERE UserId=@UserId;
   END
   ELSE IF(@MODE = 'DELETE')
   BEGIN
   DELETE FROM UserDetail WHERE UserId=@UserId;
   END
   ELSE IF(@MODE = 'ADMIN_SELECT')
   BEGIN
   SELECT * FROM UserDetail;
   END
   ELSE IF(@MODE = 'MANGER_SELECT')
   BEGIN
	select * from UserDetail where USER_TYPE in(2,3);
   END
   ELSE IF(@MODE = 'USERS_SELECT')
   BEGIN
	select * from UserDetail where USER_TYPE in(3);
   END
   ELSE IF(@MODE = 'USERS_LOG_INSERT')
   BEGIN
	 INSERT into USER_LOG(USER_NAME,LOGIN_DATE,UserId) values(@USER_NAME,SYSDATETIME(),@UserId);
   END
    ELSE IF(@MODE = 'USERS_LOGIN_SELECT')
   BEGIN
	select COUNT(*)CNT,(case when USER_TYPE=1 then 'Admin' when USER_TYPE=2 then 'Manager' else 'Users' end)USER_TYPE,UserId from UserDetail
	where USER_NAME= @USER_NAME AND USER_PASSWORD=@USER_PASSWORD
	group by USER_TYPE,UserId;
   END
    ELSE IF(@MODE = 'MANGER_REPORTS')
   BEGIN
	SELECT distinct FIRST_NAME [First Name],LAST_NAME [Last Name],LAST_LOGIN_DATE [Last Login Date],USER_CNT [Login Count]

	FROM(
			SELECT UD.FIRST_NAME,UD.LAST_NAME,convert(varchar, UL.LOGIN_DATE, 107) LAST_LOGIN_DATE
			,UD.USERID
			,ud.USER_TYPE
			FROM USERDETAIL UD LEFT JOIN USER_LOG UL
			ON UL.USERID=UD.USERID
		) AS TB1
	INNER JOIN
	(
	  SELECT USERID ,COUNT(*)USER_CNT FROM USER_LOG
	  GROUP BY USERID
	)
	AS TB2 ON TB2.USERID=TB1.USERID
	where TB1.USER_TYPE <>1
   END
   ELSE IF(@MODE = 'ADMIN_REPORTS')
   BEGIN
	SELECT distinct FIRST_NAME [First Name],LAST_NAME [Last Name],LAST_LOGIN_DATE [Last Login Date],USER_CNT [Login Count]

	FROM(
			SELECT UD.FIRST_NAME ,UD.LAST_NAME ,convert(varchar, UL.LOGIN_DATE, 107) LAST_LOGIN_DATE
			,UD.USERID
			,ud.USER_TYPE
			FROM USERDETAIL UD LEFT JOIN USER_LOG UL
			ON UL.USERID=UD.USERID
		) AS TB1
	INNER JOIN
	(
	  SELECT USERID ,COUNT(*)USER_CNT FROM USER_LOG
	  GROUP BY USERID
	)
	AS TB2 ON TB2.USERID=TB1.USERID
	--where TB1.USER_TYPE <>1
   END
     ELSE IF(@MODE = 'USER_PROFILE')
   BEGIN
	select UserId,FIRST_NAME,LAST_NAME,USER_NAME,USER_PASSWORD
	,(case when USER_TYPE=1 then 'Admin' when USER_TYPE=2 then 'Manager' else 'Users' end)USER_TYPE
	from UserDetail WHERE UserId=@UserId;
   END
END

--SELECT convert(varchar, getdate(), 107)

GO
